const ERROR_TO_BUCKET = {
  payment_timed_out: "TRANSIENT",
  gateway_technical_error: "TRANSIENT",
  bank_technical_error: "TRANSIENT",
  payment_cancelled: "CUSTOMER_ABANDONED",
  card_declined: "HARD_DECLINE",
  payment_failed: "HARD_DECLINE",
  insufficient_funds: "SOFT_DECLINE",
  incorrect_cvv: "USER_ERROR",
  card_not_enrolled: "ACTION_REQUIRED",
  card_disabled_for_online_payments: "ACTION_REQUIRED",
  debit_instrument_inactive: "ACTION_REQUIRED",
  debit_instrument_blocked: "BLOCKED",
  card_expired: "EXPIRED",
  transaction_limit_exceeded: "LIMIT_HIT",
  authentication_failed: "AUTH_FAILURE",
  payment_risk_check_failed: "FRAUD_FLAG",
  international_transaction_not_allowed: "ACTION_REQUIRED",
};

const BUCKET_POLICY = {
  TRANSIENT: {
    action: "AUTO_RETRY",
    maxAttempts: 1,
    cooldownMinutes: 10,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  CUSTOMER_ABANDONED: {
    action: "SEND_PAYMENT_LINK",
    maxAttempts: 2,
    cooldownMinutes: 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  SOFT_DECLINE: {
    action: "SEND_PAYMENT_LINK_DELAYED",
    maxAttempts: 1,
    cooldownMinutes: 24 * 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  USER_ERROR: {
    action: "PROMPT_RETRY_IMMEDIATE",
    maxAttempts: 1,
    cooldownMinutes: 0,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  ACTION_REQUIRED: {
    action: "SEND_PAYMENT_LINK_WITH_INSTRUCTIONS",
    maxAttempts: 1,
    cooldownMinutes: 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  EXPIRED: {
    action: "SEND_PAYMENT_LINK_UPDATE_METHOD",
    maxAttempts: 1,
    cooldownMinutes: 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  LIMIT_HIT: {
    action: "SEND_PAYMENT_LINK_NEXT_DAY",
    maxAttempts: 1,
    cooldownMinutes: 24 * 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  SUBSCRIPTION_HALTED: {
    action: "ESCALATE_ONLY",
    maxAttempts: 0,
    cooldownMinutes: 0,
    maxAmountForAutoAction: 0,
    requiresHuman: true,
  },
  BLOCKED: {
    action: "ESCALATE_ONLY",
    maxAttempts: 0,
    cooldownMinutes: 0,
    maxAmountForAutoAction: 0,
    requiresHuman: true,
  },
  ABANDONED_SILENT: {
    action: "SEND_PAYMENT_LINK",
    maxAttempts: 2,
    cooldownMinutes: 120,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  INVOICE_OVERDUE_MILD: {
    action: "SEND_INVOICE_REMINDER",
    maxAttempts: 2,
    cooldownMinutes: 3 * 24 * 60,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  INVOICE_OVERDUE_MODERATE: {
    action: "SEND_FIRM_INVOICE_REMINDER",
    maxAttempts: 2,
    cooldownMinutes: 5 * 24 * 60,
    maxAmountForAutoAction: 500000,
    requiresHuman: false,
  },
  INVOICE_OVERDUE_SEVERE: {
    action: "ESCALATE_ONLY",
    maxAttempts: 0,
    cooldownMinutes: 0,
    maxAmountForAutoAction: 0,
    requiresHuman: true,
  },
  HARD_DECLINE: {
    action: "AUTO_RETRY",
    maxAttempts: 1,
    cooldownMinutes: 30,
    maxAmountForAutoAction: 1000000,
    requiresHuman: false,
  },
  AUTH_FAILURE: {
    action: "AUTO_RETRY",
    maxAttempts: 1,
    cooldownMinutes: 5,
    maxAmountForAutoAction: 1000000,
    requiresHuman: true,
  },
  FRAUD_FLAG: {
    action: "ESCALATE_ONLY",
    maxAttempts: 0,
    cooldownMinutes: 0,
    maxAmountForAutoAction: 0,
    requiresHuman: true,
  },
};

const GLOBAL_CAPS = {
  maxRetriesPerEvent: 3,
  maxAutoActionAmountPaise: 1000000,
  maxActionsPerCustomerPerDay: 5,
  maxInvoiceChaseDays: 30,
};

module.exports = { ERROR_TO_BUCKET, BUCKET_POLICY, GLOBAL_CAPS };
